# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'FindFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for login

	pod 'HideKeyboardTapGestureManager', '~> 1.1'
  pod 'SideMenu', '~> 6.5'
  pod 'LoadingAlert', '~> 1.3'
  pod 'OnboardKit', '~> 1.5'
  pod 'CommonKeyboard'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  
  
end

